LoadModule proxy_module modules/mod_proxy.so
LoadModule proxy_http_module modules/mod_proxy_http.so

<VirtualHost *:80>
    DocumentRoot "/usr/local/apache2/htdocs"

    <Directory "/usr/local/apache2/htdocs">
        Require all granted
    </Directory>

    ProxyPreserveHost On
    ProxyPass "/todos" "http://backend:5000/todos"
    ProxyPassReverse "/todos" "http://backend:5000/todos"
</VirtualHost>
