version: "3.8"

services:
  backend:
    build: ./backend
    container_name: todo-backend
    volumes:
      - ./backend/todos.json:/app/todos.json

  frontend:
    build: ./frontend
    container_name: todo-frontend
    ports:
      - "8080:80"
    depends_on:
      - backend

